"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.loginValidations = exports.loginUseCase = exports.loginController = void 0;
const AccountStatusEnum_1 = require("../../enums/AccountStatusEnum");
const EmailTransporterProvider_1 = require("../../providers/implementations/EmailTransporterProvider");
const UsersRepository_1 = require("../../repositories/implementations/UsersRepository");
const GenericUseCase_1 = require("../Generic/GenericUseCase");
const LoginController_1 = require("./LoginController");
const LoginUseCase_1 = require("./LoginUseCase");
const LoginValidations_1 = require("./LoginValidations");
const emailTransporterProvider = new EmailTransporterProvider_1.EmailTransporterProvider();
const usersRepository = new UsersRepository_1.UsersRepository();
const accountStatusEnumValidation = new AccountStatusEnum_1.AccountStatusEnumValidation();
const genericUseCase = new GenericUseCase_1.GenericUseCase(usersRepository, emailTransporterProvider, accountStatusEnumValidation);
const loginUseCase = new LoginUseCase_1.LoginUseCase(usersRepository);
exports.loginUseCase = loginUseCase;
const loginValidations = new LoginValidations_1.LoginValidations(genericUseCase);
exports.loginValidations = loginValidations;
const loginController = new LoginController_1.LoginController(genericUseCase, loginUseCase, loginValidations);
exports.loginController = loginController;
