"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createUserController = exports.createUserUseCase = void 0;
const AccountStatusEnum_1 = require("../../enums/AccountStatusEnum");
const EmailTransporterProvider_1 = require("../../providers/implementations/EmailTransporterProvider");
const UsersRepository_1 = require("../../repositories/implementations/UsersRepository");
const GenericUseCase_1 = require("../Generic/GenericUseCase");
const CreateUserController_1 = require("./CreateUserController");
const CreateUserUseCase_1 = require("./CreateUserUseCase");
const CreateUserValidations_1 = require("./CreateUserValidations");
const emailTransporterProvider = new EmailTransporterProvider_1.EmailTransporterProvider();
const usersRepository = new UsersRepository_1.UsersRepository();
const accountStatusEnumValidation = new AccountStatusEnum_1.AccountStatusEnumValidation();
const genericUseCase = new GenericUseCase_1.GenericUseCase(usersRepository, emailTransporterProvider, accountStatusEnumValidation);
const createUserUseCase = new CreateUserUseCase_1.CreateUserUseCase(usersRepository, genericUseCase);
exports.createUserUseCase = createUserUseCase;
const createUserValidations = new CreateUserValidations_1.CreateUserValidations(genericUseCase);
const createUserController = new CreateUserController_1.CreateUserController(createUserUseCase, createUserValidations);
exports.createUserController = createUserController;
